"""
Generates a sample batch of 100 PDF lab reports using ReportLab.
Each PDF represents a single patient's lab result as it would come from a lab system.
"""
import pandas as pd
from datetime import datetime
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils import LANDING, RUN_DATE

PDF_SAMPLE_SIZE = 100


def generate_lab_pdfs():
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer
    except ImportError:
        print("[lab_pdfs] reportlab not installed — skipping PDF generation")
        return []

    labs_path = LANDING / "labs" / f"labs_{RUN_DATE}.csv"
    pats_path = LANDING / "patients" / f"patients_{RUN_DATE}.csv"
    if not labs_path.exists():
        print(f"[lab_pdfs] labs CSV not found — run generate_labs.py first")
        return []

    labs_df = pd.read_csv(labs_path).head(PDF_SAMPLE_SIZE)
    pats_df = pd.read_csv(pats_path, usecols=["patient_id", "first_name", "last_name", "date_of_birth"])
    pats_map = pats_df.set_index("patient_id").to_dict("index")

    styles   = getSampleStyleSheet()
    title_style = ParagraphStyle("title", fontSize=14, fontName="Helvetica-Bold", spaceAfter=6)
    header_style = ParagraphStyle("header", fontSize=10, fontName="Helvetica-Bold")
    body_style   = ParagraphStyle("body",   fontSize=9,  fontName="Helvetica")

    out_paths = []
    for idx, (_, row) in enumerate(labs_df.iterrows()):
        pat   = pats_map.get(row["patient_id"], {})
        fname = pat.get("first_name", "Unknown")
        lname = pat.get("last_name",  "Patient")
        dob   = pat.get("date_of_birth", "N/A")

        flag_color = colors.green
        if row["abnormal_flag"] == "High":
            flag_color = colors.orange
        elif row["abnormal_flag"] in ("Low", "Critical"):
            flag_color = colors.red

        out_path = LANDING / "labs" / f"lab_report_{idx+1:03d}_{RUN_DATE}.pdf"
        doc      = SimpleDocTemplate(str(out_path), pagesize=letter,
                                     leftMargin=0.75*inch, rightMargin=0.75*inch,
                                     topMargin=0.75*inch, bottomMargin=0.75*inch)

        story = [
            Paragraph("HEALTHCARE ADK — LABORATORY REPORT", title_style),
            Paragraph(f"Report Date: {row['result_date']}    |    Lab ID: {row['lab_id']}", body_style),
            Spacer(1, 0.2*inch),
            Paragraph("PATIENT INFORMATION", header_style),
        ]

        pat_table_data = [
            ["Name:",        f"{fname} {lname}",  "DOB:",    dob],
            ["Patient ID:",  row["patient_id"][:24], "Provider ID:", row["provider_id"][:24]],
            ["Order Date:",  row["order_date"],    "Result Date:", row["result_date"]],
        ]
        pat_table = Table(pat_table_data, colWidths=[1.2*inch, 2.8*inch, 1.2*inch, 2.0*inch])
        pat_table.setStyle(TableStyle([
            ("FONTNAME",  (0,0), (-1,-1), "Helvetica"),
            ("FONTSIZE",  (0,0), (-1,-1), 9),
            ("FONTNAME",  (0,0), (0,-1), "Helvetica-Bold"),
            ("FONTNAME",  (2,0), (2,-1), "Helvetica-Bold"),
            ("GRID",      (0,0), (-1,-1), 0.25, colors.lightgrey),
            ("BACKGROUND",(0,0), (-1,0),  colors.whitesmoke),
        ]))
        story.append(pat_table)
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph("RESULT SUMMARY", header_style))

        result_data = [
            ["Test Name", "LOINC", "Result", "Unit", "Ref Range", "Flag"],
            [
                row["test_name"], row["loinc_code"],
                str(row["result_value"]), row["result_unit"],
                f"{row['reference_range_low']} – {row['reference_range_high']}",
                row["abnormal_flag"],
            ]
        ]
        res_table = Table(result_data, colWidths=[1.8*inch, 0.9*inch, 0.8*inch, 0.7*inch, 1.5*inch, 0.8*inch])
        res_table.setStyle(TableStyle([
            ("FONTNAME",    (0,0), (-1,0),  "Helvetica-Bold"),
            ("FONTNAME",    (0,1), (-1,-1), "Helvetica"),
            ("FONTSIZE",    (0,0), (-1,-1), 9),
            ("BACKGROUND",  (0,0), (-1,0),  colors.HexColor("#003366")),
            ("TEXTCOLOR",   (0,0), (-1,0),  colors.white),
            ("TEXTCOLOR",   (5,1), (5,1),   flag_color),
            ("FONTNAME",    (5,1), (5,1),   "Helvetica-Bold"),
            ("GRID",        (0,0), (-1,-1), 0.25, colors.lightgrey),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.whitesmoke]),
        ]))
        story.append(res_table)
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph("This report was generated by the HealthcareADK synthetic data system. Not for clinical use.", body_style))

        doc.build(story)
        out_paths.append(out_path.name)

    print(f"[lab_pdfs]  {len(out_paths):>6,} PDFs  ->  landing_zone/labs/")
    return out_paths


if __name__ == "__main__":
    generate_lab_pdfs()

